### ISSUE TITLE
Remove references to Mercurial

### ISSUE THREAD

**Issue by agarny** [PMR2/PMR2userdocs#5]
Now that PMR2 has switched to Git, there is no and, in fact, we shouldn't be making references to Mercurial in:
 - [introduction.rst](https://github.com/PMR2/PMR2userdocs/blob/master/introduction.rst); and
 - [glossary.rst](https://github.com/PMR2/PMR2userdocs/blob/master/glossary.rst).

**Comment by metatoaster** [comment]
@agarny Please see #6.

**Comment by agarny** [comment]
Thanks @metatoaster, that looks good to me. Just a couple of minor comments.
